### PR TITLE
Fixing running on multiple hosts

### LINKED ISSUE #46: Add the option to create redis without running redis-trib
In https://github.com/idealista/redis-role/blob/master/templates/cluster-creator.sh.j2#L41, redis-trib connect to the provided IPs and configures the redis-clusters.
The IPs are provided from the play_hosts, meaning the IPs of all of the hosts in which the play occurs. This means that for each host, redis-trib will run.
This causes deadlock, since each hosts in trying to be the "first" node on the cluster, while it waits for the other clusters to join.

Therefore, when running the role on multiple hosts within one play, redis-trib should run only once for the *all* of the hosts in the play.

### LINKED ISSUE #47: When running the role on "localhost" redis cluster is trying to configure 127.0.0.1 instead of the actual IP
When running the role on "localhost" redis cluster is trying to configure 127.0.0.1 instead of the actual IP.

The IP should be taken from ansible params, and not from the host.

### PR DESCRIPTION
**Pull request by lihiwish**
This PL fix issue #47. It enables to read the play's hosts IP from ansible (which have the actual IPs), instead of reading the IPs from the hosts itselfs.

### CODE REVIEW

**Comment by jdvr** [comment]
@lihiwish How have you configured the play? There is a counter in the [cluter-creator](https://github.com/idealista/redis-role/blob/0bead5d82f8edc49f454f1dc6f614345c22db526/templates/cluster-creator.sh.j2#L21) to avoid running the redis-trib more than once. The initial idea of this role was to set `serial: 1` when redis is running as cluster. 

The two main reason set this are:
- During instillation this is the only way to ensure that all nodes are up and running before the `cluster meet`[https://github.com/idealista/redis-role/blob/0bead5d82f8edc49f454f1dc6f614345c22db526/templates/cluster-creator.sh.j2#L17]. 
- During redis upgrade this ensure each node is removed and added after been upgrade in a safe way. Performing a manual FO or resharding nodes


For the same two reason describe above, despite I think its good idea to set a variable to explicit control the automatic execution of `redis-trib`. It could be a problem to have nodes that not contains same scripts.

**Comment by lihiwish** [comment]
@jdvr Thank you for your comments. I am running the role as part of the dependencies of a different role.
I did not set `serial: 1` therefore COUNT_NODES_ON_CLUSTER was always 1.
I will add `serial: 1` to my setup and update :)

**Comment by jnogol** [comment]
Hi @lihiwish,

How is it working with `serial: 1`?

**Comment by lihiwish** [comment]
Hi @jnogol
Thanks for asking.
It might take a bit until I'll get the chance to test this. I'll update with my findings.

**Comment by lihiwish** [comment]
Hi,
`serial: 1` indeed solved the first issue.
I will update the PL to include only "reading IP of host" change

**Pull request merged**
